"""PDF builder for play-type visualization export."""

from __future__ import annotations

import io
from typing import Dict, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


def _team_label(team: str, team_names: Optional[Dict[str, str]]) -> str:
    if not team_names:
        return team
    name = team_names.get(team)
    return f"{team} ({name})" if name else team


def build_playtype_viz_pdf(
    play_type: str,
    season: str,
    our: str,
    opp: str,
    caption: str,
    png_bytes: bytes,
    w_off: float,
    w_def: float,
    k: int,
    team_names: Optional[Dict[str, str]] = None,
) -> bytes:
    """
    Build a 1-page PDF containing:
    - Title + matchup header
    - SportyPy court map image (PNG)
    - Caption with baseline numbers

    Returns raw PDF bytes.
    """
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    page_w, page_h = letter

    margin = 0.65 * inch
    y = page_h - margin

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, "Play Type Court Map (SportyPy)")
    y -= 0.28 * inch

    c.setFont("Helvetica", 11)
    matchup_line = f"{_team_label(our, team_names)} vs {_team_label(opp, team_names)} • {season}"
    c.drawString(margin, y, matchup_line)
    y -= 0.18 * inch

    c.setFont("Helvetica", 10)
    weights_line = f"Weights: w_off={float(w_off):.2f}, w_def={float(w_def):.2f}   |   Top-K: {int(k)}"
    c.drawString(margin, y, weights_line)
    y -= 0.22 * inch

    # Image placement
    img_reader = ImageReader(io.BytesIO(png_bytes))

    max_img_w = page_w - 2 * margin
    max_img_h = 6.1 * inch

    draw_w = max_img_w
    draw_h = max_img_h

    img_y = y - draw_h
    if img_y < margin + 1.2 * inch:
        available_h = y - (margin + 1.2 * inch)
        draw_h = max(3.5 * inch, available_h)
        img_y = y - draw_h

    c.drawImage(img_reader, margin, img_y, width=draw_w, height=draw_h, preserveAspectRatio=True, anchor="c")
    y = img_y - 0.18 * inch

    # Caption
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "Caption")
    y -= 0.16 * inch

    c.setFont("Helvetica", 10)
    text = c.beginText(margin, y)
    text.setLeading(13)

    words = caption.split(" ")
    line = ""
    for w in words:
        candidate = (line + " " + w).strip()
        if c.stringWidth(candidate, "Helvetica", 10) <= (page_w - 2 * margin):
            line = candidate
        else:
            text.textLine(line)
            line = w
    if line:
        text.textLine(line)

    c.drawText(text)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawRightString(page_w - margin, margin * 0.75, "Generated by Basketball Strategy Analysis (Capstone)")
    c.showPage()
    c.save()

    buf.seek(0)
    return buf.read()
